### PR TITLE
DMT-53 Merge labels position to dev

### LINKED ISSUE #50: Labels locations
Would be nice to be able to change labels positions from inside to outside

### PR DESCRIPTION
**Pull request by chrytsa**
## Related issue
- Closes #50

## Proposed changes
- Allow the visualization of the labels' text not only inside of the sectors, but also outside of them
- Add functionality to resposively align and visualize the labels' text, when the `Outside chart` option is selected via the popout settings option. 

## Additional information // Optional
- Refactor the logic for displaying labels
- Introduce the `labels.js` class, responsible for handling the functionality related to the labels

### CODE REVIEW

**Review by eemilj — APPROVED** [review]
Everything seems to be working nicely, tested locally, good job!

**Comment by chrytsa** [comment]
> Everything seems to be working nicely, tested locally, good job!

Nice! :+1: Can it be merged then?

**Comment by eemilj** [comment]
Yes! It's approved! I'll press the button I guess then 😄

**Comment by chrytsa** [comment]
> Yes! It's approved! I'll press the button I guess then smile

Yeah, was a bit hesitant to proceed, since me and Krasen worked on this! :smiley:

**Pull request merged**
